apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql
spec:
  containers:
    - image: mysql:5.7
      ports:
        - containerPort: 3306
      name: mysql
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "abc123"
        - name: "MYSQL_DATABASE"
          value: "wordpress"
        - name: "MYSQL_USER"
          value: "wordpress"
        - name: "MYSQL_PASSWORD"
          value: "abc123"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: mysql
  name: mysql-service
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    name: mysql